package problem2;

/*
 * Each new term in the Fibonacci sequence is generated by adding 
 * the previous two terms. By starting with 1 and 2, the first 10 
 * terms will be:
 * 
 * 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 * 
 * By considering the terms in the Fibonacci sequence whose values 
 * do not exceed four million, find the sum of the even-valued terms.
 * */

public class SumEvenFib {
	public static void main(String[] args) {
		int first = 1;
		int second = 1;
		int limit = 4000000;
		int evenSum = 0;
		boolean toggle = false;
		
		while (first < limit && second < limit) {
			if (toggle) {
				first = first + second;
				if (first % 2 == 0 && first < limit) {
					evenSum += first;
				}
			}
			else {
				second = first + second;
				if (second % 2 == 0 && second < limit) {
					evenSum += second;
				}
			}
			toggle = !toggle;
		}
		System.out.println("Sum of even fibonacci numbers under limit is: " + evenSum);
	}
}
